homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
]

statistik/urls.py
from django.urls import path
from . import views

app_name = 'statistik'

urlpatterns = [
    path('', views.statCovid, name='persentasecovid'),
    path('results/', views.statCovid_ajax, name="ajaxstats"),
    path('reset/', views.cobaLagi, name='reset'),
]

tk2/urls.py
from django.urls import path, include
from django.contrib import admin
from rest_framework.urlpatterns import format_suffix_patterns
from simulasi import views as simulasi_view
from rating import views as rating_view
from feedback import views as feedback_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('rating/',include('rating.urls')),
    path('simulasi/', include('simulasi.urls')),
    path('simulasi/positif/', simulasi_view.PendudukList.as_view()),
    path('persentasecovid/', include('statistik.urls')),
    path('feedback/', include('feedback.urls')),
    path('feedback/data/',feedback_view.feedbackList.as_view()),
    path('',include("django.contrib.auth.urls")),
    path('signup/',include('register.urls')),
    path('rating/akun/',rating_view.AkunList.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

statistik/models.py
from django.db import models

class PersentaseStatus(models.Model):
    positif = models.PositiveIntegerField()
    negatif = models.PositiveIntegerField()
        
class PersentaseJenisKelamin(models.Model):
    pria = models.PositiveIntegerField()
    perempuan = models.PositiveIntegerField()
        
class PersentaseUmur(models.Model):
    muda = models.PositiveIntegerField()
    tengah = models.PositiveIntegerField()
    dewasa = models.PositiveIntegerField()
    tua = models.PositiveIntegerField()

statistik/views.py
from django.shortcuts import render, redirect
from simulasi.models import JumlahPendudukAwal
from simulasi.models import Penduduk
from .models import PersentaseStatus
from .models import PersentaseJenisKelamin
from .models import PersentaseUmur
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
import json

@login_required
def statCovid(request):

    # statistik awal
    persen_positif = 0
    persen_negatif = 0
    persen_pria = 0
    persen_perempuan = 0
    persen_muda = 0
    persen_dewasa = 0
    persen_tengah = 0
    persen_tua = 0

    # membuat objek untuk setiap model untuk menyimpan data
    PersentaseStatus.objects.create(positif=persen_positif, negatif=persen_negatif)
    PersentaseJenisKelamin.objects.create(pria=persen_pria, perempuan=persen_perempuan)
    PersentaseUmur.objects.create(muda=persen_muda, tengah=persen_tengah, dewasa=persen_dewasa, tua=persen_tua)

    # untuk mengakses objek yang sudah dibuat
    status = PersentaseStatus.objects.all()[0]
    gender = PersentaseJenisKelamin.objects.all()[0]
    umur = PersentaseUmur.objects.all()[0]

    jumlah_awal = JumlahPendudukAwal.objects.all().count()

    if JumlahPendudukAwal.objects.all().count() > 0 and Penduduk.objects.filter(status_covid='Positif').count() == 0:
        persen_negatif = 100

    elif Penduduk.objects.filter(status_covid='Positif').count() > 0:
        
        awal = JumlahPendudukAwal.objects.all()[0]
        total = awal.jumlah + Penduduk.objects.all().count()
        
        # statistik berdasarkan status covid
        jumlah_positif = Penduduk.objects.filter(status_covid='Positif').count()
        persen_positif = jumlah_positif * 100 // total
        persen_negatif = 100 - persen_positif

        # statistik berdasarkan jenis kelamin
        jumlah_pria = Penduduk.objects.filter(status_covid='Positif', jenis_kelamin='Laki-Laki').count()
        persen_pria = jumlah_pria * 100 // jumlah_positif
        persen_perempuan = 100 - persen_pria

        # statistik berdasarkan usia
        usiaMuda = 0
        usiaDewasa = 0
        usiaTengah = 0
        usiaTua = 0

        for penduduk in Penduduk.objects.filter(status_covid='Positif'):
            if int(penduduk.usia) <= 20:
                usiaMuda += 1

            elif int(penduduk.usia) > 20 and int(penduduk.usia) < 45:
                usiaDewasa += 1

            elif int(penduduk.usia) >= 45 and int(penduduk.usia) <= 65:
                usiaTengah += 1

            else:
                usiaTua +=1
        
        persen_muda = usiaMuda * 100 // jumlah_positif
        persen_dewasa = usiaDewasa * 100 // jumlah_positif
        persen_tengah = usiaTengah * 100 // jumlah_positif
        persen_tua = usiaTua * 100 // jumlah_positif

    status.positif = persen_positif
    status.negatif = persen_negatif
    status.save()

    gender.pria = persen_pria
    gender.perempuan = persen_perempuan
    gender.save()

    umur.muda = persen_muda
    umur.tengah = persen_tengah
    umur.dewasa = persen_dewasa
    umur.tua = persen_tua
    umur.save()

    response = {
        'status': status,
        'gender': gender,
        'umur': umur,
        'awal': jumlah_awal
    }
    return render(request, 'stats.html', response)

@login_required
def statCovid_ajax(request):

    data = dict()
    data['positif'] = PersentaseStatus.objects.all()[0].positif
    data['negatif'] = PersentaseStatus.objects.all()[0].negatif
    data['pria'] = PersentaseJenisKelamin.objects.all()[0].pria
    data['perempuan'] = PersentaseJenisKelamin.objects.all()[0].perempuan
    data['muda'] = PersentaseUmur.objects.all()[0].muda
    data['tengah'] = PersentaseUmur.objects.all()[0].tengah
    data['dewasa'] = PersentaseUmur.objects.all()[0].dewasa
    data['tua'] = PersentaseUmur.objects.all()[0].tua

    response = {
        'data': data,
    }
    return JsonResponse(response)

@login_required
def cobaLagi(request):

    JumlahPendudukAwal.objects.all().delete()
    Penduduk.objects.all().delete()
    PersentaseStatus.objects.all().delete()
    PersentaseJenisKelamin.objects.all().delete()
    PersentaseUmur.objects.all().delete()

    return redirect('/simulasi/jumlah')

statistik/templates/header.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	
	
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="/static/styles.css">
	<link rel="stylesheet" href="/static/styleh.css">
    <link rel="stylesheet" href="/static/stylef.css">
    <link rel="stylesheet" href="/static/index.css">
	<link rel="icon" href="{% static 'logo.png' %}">
	
	<title>
		{% block title %}{% endblock %}
	</title>
</head>
<body>
	<nav class="navbar navbar-expand-sm navbar-dark" style="background-color: #6FCF97;font-size: 20px;">
	  <ul class="navbar-nav">
	    <li class="nav-item active">
	      <a class="nav-link" href="{% url 'homepage:index' %}">C19 Simulation</a>
	    </li>
		<li class="navbar-nav">
			<a class="nav-link" href="/simulasi/jumlah">Simulasi</a>
		</li>
		<li class="navbar-nav">
			<a class="nav-link" href="/simulasi/daftarpositif">Daftar Positif</a>
		</li>
		<li class="navbar-nav">
			<a class="nav-link" href="{% url 'statistik:persentasecovid' %}">Persentase Covid</a>
		</li>
		<li class="navbar-nav">
			<a class="nav-link" href="/feedback/">Feedback</a>
		</li>
		<li class="navbar-nav">
			<a class="nav-link" href="{% url 'rating:halaman_signup' %}">Rating</a>
		</li>
	  </ul>
	   <ul class="navbar-nav">
	  	{% if user.is_authenticated %}
	  	<li class="nav-item">
	  		<a class="nav-link" href="/logout/">Logout</a>
	  	</li>
	  	{% else %}
	  	<li class="nav-item">
	  		<a class="nav-link" href="/login/">Login</a>
	  	</li>
	  	<li class="nav-item">
	  		<a class="nav-link" href="/signup/">Sign Up</a>
	  	</li>
	  	{% endif %}
	  </ul>

	</nav>

	{% block content %}{% endblock %}
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

statistik/templates/stats.html
{% extends 'header.html' %}
{% load static %}
{% block title %}Persentase Covid{% endblock %}

{% block content %}

{% if awal == 0 %}
<center>
	<p style="font-size: 24px"><b>Data belum dimasukkan. Silahkan mulai simulasi!</b></p>
	<a href="/simulasi/jumlah">
		<button id="simulasi" class="btn button-custom" style="background-color: #6FCF97; color:white; font-size: 20px">Mulai Simulasi</button>
	</a>
</center>

{% else %}
<center>
	<form action=""> 
		<select class="filter">
			<option value="placeholder">Filter by...</option>
			<option value="semua">Semua</option>
			<option value="status">Status COVID-19</option>
			<option value="gender">Jenis Kelamin</option>
			<option value="umur">Umur</option>
		</select>
	</form>
</center>
<br>

<div class="containerpair" id="statistik" style="margin-top: 2%;">

</div>
<br>
<br>
<center>
	<div class="a">
		Terima kasih sudah mencoba C19 Simulation 
		<br>
		Ingat, selalu jaga kesehatan di masa pandemi ini.
		<br>
		<br>
		<p style="font-size: 24px"><b>Sampai Jumpa Lagi!</b></p>
		<br>
		<a href="{% url 'statistik:reset' %}">
			<button id="reset" class="btn button-custom" style="background-color: #6FCF97; color:white; font-size: 20px">Coba Lagi</button>
		</a>
		<br>
		<br>
	</div>
</center>
{% endif %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="/static/statistik.js"></script>

{% endblock %}