covidsimulasi/urls.py
from django.urls import path
from . import views

app_name = 'covidsimulasi'

urlpatterns = [
    path('', views.index, name='index'),
]

rating/urls.py
from django.urls import path
from . import views

app_name = 'rating'

urlpatterns = [
    path('',views.halaman_rating, name='halaman_rating'),
    path('ratingwebkami/',views.halaman_form,name='halaman_form'),
    path('berhasil/',views.feedback_form,name='feedback_form'),
    path('editrating/',views.edit_rating,name='edit_rating'),
]

statistik/urls.py
from django.urls import path
from . import views

app_name = 'statistik'

urlpatterns = [
    path('', views.statCovid, name='persentasecovid'),
    path('results/', views.statCovid_ajax, name="ajaxstats"),
    path('reset/', views.cobaLagi, name='reset'),
]

tk2/urls.py
from django.urls import path, include
from django.contrib import admin
from rest_framework.urlpatterns import format_suffix_patterns
from simulasi import views as simulasi_view
from rating import views as rating_view
from feedback import views as feedback_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('rating/',include('rating.urls')),
    path('simulasi/', include('simulasi.urls')),
    path('simulasi/positif/', simulasi_view.PendudukList.as_view()),
    path('persentasecovid/', include('statistik.urls')),
    path('feedback/', include('feedback.urls')),
    path('feedback/data/',feedback_view.feedbackList.as_view()),
    path('',include("django.contrib.auth.urls")),
    path('signup/',include('register.urls')),
    path('rating/akun/',rating_view.AkunList.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

covidsimulasi/models.py
from django.db import models

# Create your models here.

covidsimulasi/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

covidsimulasi/templates/header.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	
	
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'index.css' %}">
	<link rel="stylesheet" href="{% static 'styles.css' %}">
	
	<title>
		{% block title %}{% endblock %}
	</title>
</head>
<body>
	<nav class="navbar navbar-expand-sm navbar-dark" style="background-color: #6FCF97;font-size: 20px;">
	  <ul class="navbar-nav">
	    <li class="nav-item active">
	      <a class="nav-link" href="{% url 'covidsimulasi:index' %}">C19 Simulation</a>
	    </li>
		<li class="navbar-nav">
			<a class="nav-link" href="/simulasi/jumlah">Simulasi</a>
		</li>
		<li class="navbar-nav">
			<a class="nav-link" href="/simulasi/daftarpositif">Daftar Positif</a>
		</li>
		<li class="navbar-nav">
			<a class="nav-link" href="{% url 'statistik:persentasecovid' %}">Persentase Covid</a>
		</li>
		<li class="navbar-nav">
			<a class="nav-link" href="#">Feedback</a>
		</li>
		<li class="navbar-nav">
			<a class="nav-link" href="{% url 'rating:halaman_form' %}">Rating</a>
		</li>
	  </ul>

	</nav>

	{% block content %}{% endblock %}
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

covidsimulasi/templates/index.html
{% extends "header.html" %}
{% load static %}
{% block title %}C19 Simulation{% endblock %}

{% block content %}

<div class="container font-web" style="text-align: center;font-family: Georgia, 'Times New Roman', Times, serif;margin-top: 150px;">
	<h1><b>Selamat Datang di Website C19Simulation !!</b></h1>
	<h3 style="margin-top: 40px">Web ini akan membantu anda membuat simulasi covid di suatu daerah X dengan asumsi seluruh penduduk awal berstatus negatif</h3>
	<h3 style="margin-top: 40px"><b>Selamat Mencoba</b></h3>
	<a class="btn button-custom" href="/simulasi/jumlah" style="margin-top: 30px;background-color: #6FCF97;color:white">Mulai !!</a>
</div>
{% endblock %}