homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
]

rating/urls.py
from django.urls import path
from . import views

app_name = 'rating'

urlpatterns = [
    path('',views.halaman_rating, name='halaman_rating'),
    path('ratingwebkami/',views.halaman_form,name='halaman_form'),
    path('berhasil/',views.feedback_form,name='feedback_form'),
    path('editrating/',views.edit_rating,name='edit_rating'),
]

statistik/urls.py
from django.urls import path
from . import views

app_name = 'statistik'

urlpatterns = [
    path('', views.statCovid, name='persentasecovid'),
    path('results/', views.statCovid_ajax, name="ajaxstats"),
    path('reset/', views.cobaLagi, name='reset'),
]

tk2/urls.py
from django.urls import path, include
from django.contrib import admin
from rest_framework.urlpatterns import format_suffix_patterns
from simulasi import views as simulasi_view
from rating import views as rating_view
from feedback import views as feedback_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('rating/',include('rating.urls')),
    path('simulasi/', include('simulasi.urls')),
    path('simulasi/positif/', simulasi_view.PendudukList.as_view()),
    path('persentasecovid/', include('statistik.urls')),
    path('feedback/', include('feedback.urls')),
    path('feedback/data/',feedback_view.feedbackList.as_view()),
    path('',include("django.contrib.auth.urls")),
    path('signup/',include('register.urls')),
    path('rating/akun/',rating_view.AkunList.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

homepage/templates/header.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	
	
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<link rel="stylesheet" href="/static/styles.css">
	<link rel="stylesheet" href="/static/styleh.css">
    <link rel="stylesheet" href="/static/stylef.css">
    <link rel="stylesheet" href="/static/index.css">
	<link rel="icon" href="{% static 'logo.png' %}">
	<title>
		{% block title %}{% endblock %}
	</title>
</head>
<body>
	<nav class="navbar navbar-expand-sm navbar-dark" style="background-color: #6FCF97;font-size: 20px;">
	  <ul class="navbar-nav mr-auto">
	    <li class="nav-item active">
	      <a class="nav-link" href="{% url 'homepage:index' %}">C19 Simulation</a>
	    </li>
		<li class="navbar-nav">
			<a class="nav-link" href="/simulasi/jumlah">Simulasi</a>
		</li>
		<li class="navbar-nav">
			<a class="nav-link" href="/simulasi/daftarpositif">Daftar Positif</a>
		</li>
		<li class="navbar-nav">
			<a class="nav-link" href="{% url 'statistik:persentasecovid' %}">Persentase Covid</a>
		</li>

		<li class="navbar-nav">
			<a class="nav-link" href="/feedback/">Feedback</a>
		</li>
		<li class="navbar-nav">
			<a class="nav-link" href="{% url 'rating:halaman_rating' %}">Rating</a>
		</li>
	  </ul>
	  <ul class="navbar-nav">
	  	{% if user.is_authenticated %}
	  	<li class="nav-item">
	  		<a class="nav-link" href="/logout/">Logout</a>
	  	</li>
	  	{% else %}
	  	<li class="nav-item">
	  		<a class="nav-link" href="/login/">Login</a>
	  	</li>
	  	<li class="nav-item">
	  		<a class="nav-link" href="/signup/">Sign Up</a>
	  	</li>
	  	{% endif %}
	  </ul>



	</nav>

	{% block content %}{% endblock %}
</body>
</html>

homepage/templates/index.html
{% extends 'header.html' %}
{% load static %}

{% block title %}C19 Simulation{% endblock title %}

{% block content %}
<div class = "container">
  {% if user.is_authenticated %}
  <div class="alert alert-success mt-4 messages">
      <h3>Welcome, {{ user.get_username }}</h3>
  </div>
  {% else %}
  {% endif %}
  <div class = "row justify-content-around" style = "padding:50px; padding-top:100px">
    <div class = "col-md-4" style = "padding:20px">
      <img src="{% static 'h3.png' %}"  id = "img1">
    </div>
    <div class = "col-md-8">
      <h1 class = "title1">C-19 Simulation</h1>
      <p>Web ini akan membantu kalian dalam bersimulasi untuk menjadi pengurus daerah X dari COVID-19 dengan asumsi seluruh penduduk
        awalnya berstatus negatif</p>
      <p style = "padding:20px"><a href = "simulasi/jumlah/" class = "btn button">>> Mulai simulasi >> </a></p>
    </div>
  </div>
  <div class = "row justify-content-around" style = "padding:50px;">
    <h2 class = "title1 align-self-center">Sekilas tentang Covid-19</h2>
    <div class = "col-md-8" style = "padding:20px">
      <p>Covid-19 adalah virus yang bisa menular dengan cepat sehingga dapat dibilang sebagai
        virus yang mematikan. COVID-19 atau Corona beredar di Indonesia sejak Maret 2019 yang lalu</p>
      <p>Menurut survey, sebagian besar (sekitar 80%) orang yang terinfeksi telah berhasil pulih 
        tanpa perlu perawatan khusus, dan sekitar 1 dari 5 orang yang terinfeksi COVID-19 
        menderita sakit parah dan kesulitan bernapas.</p>
    </div>
    <div class = "col-md-4" style = "padding:20px">
      <img src="{% static 'h2.png' %}"  id = "img2">
    </div>
  </div>
  <h3 class = "title1" style="padding-left:50px; padding-top:30px; padding-bottom:20px; 
    ">Data korban Covid-19 di Indonesia</h3>
  <div class = "row d-flex justify-content-around text-center" style = "padding-left:50px;padding-right: 50px" >
    <div class = "col-md-4">
      <p>Total Kasus :</p>
      <p>488 rb</p>
    </div>
    <div class = "col-md-4">
      <p>Total Sembuh :</p>
      <p>411 rb</p>
    </div>
    <div class = "col-md-4">
      <p>Total Meninggal Dunia :</p>
      <p>15,6 rb</p>
    </div>
  </div>
  <center>
  <br><small>Terakhir update tanggal : 21/11/2020</small><br><br>
  </center>
  <div style = "padding:50px">
    <h2 class = "title1 text-right"> Sekilas tentang Aplikasi </h2>
    <div class = "row d-flex justify-content-around">
      <div class ="col-md-4">
        <img src = "{% static 'h4.png' %}" id = "img1">
      </div>
      <div class = "col-md-8">
        <p class = "text-right">Mula-mula semua warga desa X tidak ada yang terinfeksi COVID-19, sehingga untuk menghindari 
          penularan COVID 19 yang bisa meresahkan warga sekitar, kita sebagai pengurus warga harus 
          mendata semua warga baru/pengunjung baik itu nama, jenis kelamin, usia, alamat dimana 
          dia akan tinggal di daerah X, serta status COVID-19 apakah dia terinfeksi atau tidak.</p>
        <p class = "text-right">Lalu apabila dia positif, maka kamu diwajibkan untuk mengarantina dia supaya warga desa 
          tidak ada yang terinfeksi. Orang tersebut juga nantinya bisa disembuhkan atau dibiarkan. 
          Dan terakhir akan dihitung persentase warga daerah X yang terkena positif COVID-19, 
          termasuk warga baru/pengunjung.</p>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){
      $(".messages").click(function(){
        $(".messages").fadeOut();
      });
    });
</script>
{% endblock content %}